USER_DATA_INTENT = {
    "\"FULL_NAME\"": "{",
    "\"value\"": "\"Experienced AI Engineer and Full-Stack Developer with 5+ years developing machine learning solutions, computer vision systems, and full-stack applications. Specialized in AI automation, NLP, enterprise-scale deployments, and modern web technologies. Proven track record of delivering 15+ full-stack projects and 12+ AI solutions.\",",
    "\"description\"": "\"Professional summary\"",
    "\"PHONE\"": "{",
    "\"EMAIL\"": "{",
    "\"PASSWORD\"": "{",
    "\"LINKEDIN\"": "{",
    "\"CV_PATH\"": "{",
    "\"LOCATION\"": "{",
    "\"KEYWORD\"": "{",
    "\"EDUCATION_MASTERS\"": "{",
    "\"EDUCATION_BACHELORS\"": "{",
    "\"CURRENT_POSITION\"": "{",
    "\"EXPERIENCE_YEARS\"": "{",
    "\"CURRENT_COMPANY\"": "{",
    "\"WORK_DURATION\"": "{",
    "\"PYTHON_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Years of experience with Python\"},",
    "\"JAVASCRIPT_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Years of experience with JavaScript\"},",
    "\"REACT_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Years of experience with React\"},",
    "\"TYPESCRIPT_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Years of experience with TypeScript\"},",
    "\"NODEJS_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Years of experience with Node.js\"},",
    "\"EXPRESS_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Years of experience with Express.js\"},",
    "\"FULLSTACK_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Full-stack development experience\"},",
    "\"FRONTEND_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Frontend development experience\"},",
    "\"BACKEND_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Backend development experience\"},",
    "\"MACHINE_LEARNING_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Years of ML experience\"},",
    "\"DEEP_LEARNING_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Years of deep learning experience\"},",
    "\"TENSORFLOW_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with TensorFlow\"},",
    "\"PYTORCH_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with PyTorch\"},",
    "\"NLP_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with NLP\"},",
    "\"COMPUTER_VISION_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with computer vision\"},",
    "\"AI_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Overall AI experience\"},",
    "\"DATA_SCIENCE_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Data science experience\"},",
    "\"SCIKIT_LEARN_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with Scikit-learn\"},",
    "\"AWS_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with AWS\"},",
    "\"DOCKER_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with Docker\"},",
    "\"KUBERNETES_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with Kubernetes\"},",
    "\"CLOUD_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"General cloud experience\"},",
    "\"DEVOPS_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"DevOps experience\"},",
    "\"SQL_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with SQL\"},",
    "\"MYSQL_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with MySQL\"},",
    "\"POSTGRESQL_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with PostgreSQL\"},",
    "\"MONGODB_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with MongoDB\"},",
    "\"DATABASE_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"General database experience\"},",
    "\"FIREBASE_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with Firebase\"},",
    "\"HTML_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with HTML\"},",
    "\"CSS_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with CSS\"},",
    "\"WEB_DEVELOPMENT_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with web development\"},",
    "\"RESPONSIVE_DESIGN_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Responsive design experience\"},",
    "\"FIGMA_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"Experience with Figma\"},",
    "\"UI_UX_EXPERIENCE\"": "{\"value\": \"5\", \"description\": \"UI/UX design experience\"},",
    "\"FULLSTACK_PROJECTS\"": "{\"value\": \"15\", \"description\": \"Number of full-stack projects completed\"},",
    "\"AI_PROJECTS\"": "{\"value\": \"12\", \"description\": \"Number of AI projects completed\"},",
    "\"WEB_PROJECTS\"": "{\"value\": \"20\", \"description\": \"Number of web projects completed\"},",
    "\"MACHINE_LEARNING_PROJECTS\"": "{\"value\": \"10\", \"description\": \"Number of ML projects completed\"},",
    "\"AUTOMATION_PROJECTS\"": "{\"value\": \"8\", \"description\": \"Number of automation projects completed\"},",
    "\"FIGMA_DESIGNS\"": "{\"value\": \"Yes\", \"description\": \"Can design using Figma\"},",
    "\"PORTFOLIO_AVAILABLE\"": "{\"value\": \"Yes\", \"description\": \"Has an online portfolio\"},",
    "\"GITHUB_AVAILABLE\"": "{\"value\": \"Yes\", \"description\": \"Has a GitHub profile\"},",
    "\"AI_CHATGPT_EXPERIENCE\"": "{\"value\": \"Yes\", \"description\": \"Experience using ChatGPT/LLMs\"},",
    "\"CODING_ASSISTANT_EXPERIENCE\"": "{\"value\": \"Yes\", \"description\": \"Uses AI for coding assistance\"},",
    "\"TEAM_COLLABORATION\"": "{\"value\": \"Yes\", \"description\": \"Collaborates well in teams\"},",
    "\"AGILE_EXPERIENCE\"": "{\"value\": \"Yes\", \"description\": \"Familiar with Agile development\"},",
    "\"CI_CD_EXPERIENCE\"": "{\"value\": \"Yes\", \"description\": \"Experience with CI/CD pipelines\"},",
    "\"KEY_SKILLS\"": "{",
    "\"AI_FRAMEWORKS\"": "{",
    "\"PROGRAMMING_LANGUAGES\"": "{",
    "\"CLOUD_PLATFORMS\"": "{",
    "\"DATABASES\"": "{",
    "\"WEB_TECHNOLOGIES\"": "{",
    "\"SUMMARY\"": "{",
    "EMAIL": "abdulcui54455@gmail.com",
    "PASSWORD": "690854455",
    "KEYWORD": "python ",
    "LOCATION": "pakistan",
    "CV_PATH": "D:\\AI AUTOMATION\\web scrapping\\linkedln project\\New folder\\resume.pdf"
}